name: Test and Deploy to prod Auth0
on:
  push:
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '* * 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: development
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: actions/setup-node@v2-beta
      with:
        node-version: "12"
    - name: NPM Install
      run: npm i -g auth0-deploy-cli
    # - name: remove files
    #   run: rm -rf ./src/test ./src/test-prod
    # - name: Commit files
    #   run: |
    #     git config --local user.email "kevxu@my.yorku.ca"
    #     git config --local user.name "Kai Xu"
    #     git add .
    #     git commit -m "remove files" -a
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: development
    - name: Create prod changes
      run: |
        a0deploy export --config_file ./src/prod/config.json --format directory --output_folder ./src/test-prod
    - name: Create dev changes
      run: |
        a0deploy export --config_file ./src/dev/config.json --format directory --output_folder ./src/test
    - name: check for changes
      run: |
        if git diff --exit-code; then
          echo "::set-env name=changes_exist::false"
        else
          echo "::set-env name=changes_exist::true"
        fi
    - name: Commit files
      if: ${{ env.changes_exist == 'true' }}
      run: |
        echo ${{ github.ref }}
        git config --local user.email "kevxu@my.yorku.ca"
        git config --local user.name "Kai Xu"
        git add .
        git commit -m "Add changes" -a
    - name: Push changes
      if: ${{ env.changes_exist == 'true' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: development