name: Test
on: 
  push:
    paths:
    - 'src/dev/**'
    - 'src/prod/**'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'ref/head/master' && github.ref != 'ref/head/development'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: development
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: actions/setup-node@v2-beta
      with:
        node-version: "12"
    - name: NPM Install
      run: npm i -g auth0-deploy-cli    
    - name: Create prod changes
      run: |
        a0deploy export --config_file ./src/prod/config.json --format directory --output_folder ./src/test-prod1
    - name: Create dev changes
      run: |
        a0deploy export --config_file ./src/dev/config.json --format directory --output_folder ./src/test1
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        git config --local user.email "kevxu@my.yorku.ca"
        git config --local user.name "Kai Xu"
        git add .
        git commit -m "Add changes" -a
        OUTPUT=$(git status --porcelain)
        echo ${{ OUTPUT }}
    if: OUTPUT != ''
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: development